# ingestion/Dockerfile
FROM python:3.10-slim

WORKDIR /app

COPY ingestion/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ingestion/ .
COPY data/ /data/

CMD ["python", "main.py"]